version: '3.8'

services:
  # Frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pi-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://api:5000}
    restart: unless-stopped

  # Backend
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pi-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
